version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./server:/app